library;

import 'package:pdf/pdf.dart';
import 'package:pdf/widgets.dart' as pw;
import 'package:printing/printing.dart';
import 'package:intl/intl.dart';
import '../models/weather_model.dart';
import '../models/forecast_model.dart';

class PdfService {
  /// Generate a weather report PDF
  Future<void> generateAndShareReport({
    required WeatherModel weather,
    List<DailyForecast>? forecasts,
  }) async {
    final pdf = pw.Document();
    final now = DateTime.now();

    pdf.addPage(
      pw.MultiPage(
        pageFormat: PdfPageFormat.a4,
        margin: const pw.EdgeInsets.all(40),
        build: (context) => [
          // Header
          pw.Header(
            level: 0,
            child: pw.Row(
              mainAxisAlignment: pw.MainAxisAlignment.spaceBetween,
              children: [
                pw.Text('Smart Weather Monitor Pro',
                  style: pw.TextStyle(fontSize: 20, fontWeight: pw.FontWeight.bold)),
                pw.Text(DateFormat('MMM d, yyyy - hh:mm a').format(now),
                  style: const pw.TextStyle(fontSize: 12)),
              ],
            ),
          ),
          pw.SizedBox(height: 10),
          pw.Text('Weather Report: ${weather.cityName}, ${weather.country}',
            style: pw.TextStyle(fontSize: 16, fontWeight: pw.FontWeight.bold)),
          pw.SizedBox(height: 20),

          // Current Weather Table
          pw.TableHelper.fromTextArray(
            headerStyle: pw.TextStyle(fontWeight: pw.FontWeight.bold),
            cellAlignment: pw.Alignment.centerLeft,
            headerDecoration: const pw.BoxDecoration(color: PdfColors.blue50),
            headers: ['Parameter', 'Value'],
            data: [
              ['Temperature', '${weather.temperature.round()}°C'],
              ['Feels Like', '${weather.feelsLike.round()}°C'],
              ['Condition', weather.capitalizedDescription],
              ['Humidity', '${weather.humidity}%'],
              ['Wind Speed', '${weather.windSpeedKmh.toStringAsFixed(1)} km/h'],
              ['Pressure', '${weather.pressure} hPa'],
              ['Visibility', '${weather.visibilityKm.toStringAsFixed(1)} km'],
              ['UV Index', '${weather.estimatedUvIndex}'],
              ['Air Quality', '${weather.estimatedAqi} (${weather.aqiLabel})'],
              ['Sunrise', DateFormat('hh:mm a').format(weather.sunriseTime.toLocal())],
              ['Sunset', DateFormat('hh:mm a').format(weather.sunsetTime.toLocal())],
            ],
          ),

          // Forecast section
          if (forecasts != null && forecasts.isNotEmpty) ...[
            pw.SizedBox(height: 20),
            pw.Text('5-Day Forecast',
              style: pw.TextStyle(fontSize: 14, fontWeight: pw.FontWeight.bold)),
            pw.SizedBox(height: 10),
            pw.TableHelper.fromTextArray(
              headerStyle: pw.TextStyle(fontWeight: pw.FontWeight.bold),
              headerDecoration: const pw.BoxDecoration(color: PdfColors.blue50),
              headers: ['Day', 'Min', 'Max', 'Condition', 'Wind', 'Rain %'],
              data: forecasts.map((f) => [
                DateFormat('EEE, MMM d').format(f.date),
                '${f.tempMin.round()}°C',
                '${f.tempMax.round()}°C',
                f.weatherCondition,
                '${(f.maxWindSpeed * 3.6).round()} km/h',
                '${(f.maxPop * 100).round()}%',
              ]).toList(),
            ),
          ],

          pw.SizedBox(height: 30),
          pw.Divider(),
          pw.SizedBox(height: 10),
          pw.Text('Generated by Smart Weather Monitor Pro',
            style: const pw.TextStyle(fontSize: 10, color: PdfColors.grey600)),
        ],
      ),
    );

    await Printing.sharePdf(bytes: await pdf.save(), filename: 'weather_report_${weather.cityName}.pdf');
  }
}
